In [269]:
import numpy as np

In [270]:
s = '1, 2, 3, 4, 5.0, 6, 7, 8, 9, 10'
l = list(map(float, s.split(',')))

V1 = np.array(l)
V2 = np.array(l[-2])
V3 = np.array(l[::-1])
V4 = np.array([l[i] for i in range(0,len(l),3)])
V5 = np.array([i for i in range(len(l))])

In [271]:

a = list(map(int, '1, 2, 3, 4'.split(',')))
b = list(map(int, '10, 20, 30, 40'.split(',')))
V1 = np.array(a)
V2 = np.array(b)
V3 = V1 + V2
V4 = V1[::2]*V2[::-2]

In [272]:

x = '1, 2, 3, 4, 5, 6'
y = '1, 2, 3, 4'
xl = list(map(int, x.split(',')))
yl = list(map(int, y.split(',')))
V1 = np.array(xl)
V2 = np.array(yl)
V = np.array(V1[V1 % V2[-2] == 0] / V2[-2])

In [273]:
A1 = np.array((-1, 1))
A2 = np.array((2, 5))
A3 = np.array((5, -3))

a = A2 - A1
b = A3 - A2
c = A3 - A1
la = np.sqrt(a[0]**2 + a[1]**2)
lb = np.sqrt(b[0]**2 + b[1]**2)
lc = np.sqrt(c[0]**2 + c[1]**2)
p = (la+lb+lc)/2
s = np.sqrt(p*(p-la)*(p-lb)*(p-lc))
print(round(s, 4))


18.0


In [274]:
def f1(x):
    return np.sin(x*np.pi/6)
def f2(x):
    return np.exp(x)

M1 = np.array((
    (1., 2., 3., 0.),
    (4., 5., 6., 0.),
    (0., 1., 1., 6.),
    (7., 8., 9., 0.)
))

M2 = M1
x, y = M1.shape

M2[-2] = f1(M1[-2])
M2[:,-2] = f2(M2[:,-2])



4 4

[[1.00000000e+00 2.00000000e+00 2.00855369e+01 0.00000000e+00]
 [4.00000000e+00 5.00000000e+00 4.03428793e+02 0.00000000e+00]
 [0.00000000e+00 5.00000000e-01 1.64872127e+00 1.22464680e-16]
 [7.00000000e+00 8.00000000e+00 8.10308393e+03 0.00000000e+00]]
