In [83]:
import numpy as np

# #31

In [84]:
# oldSettings = np.seterr(all='ignore')

# #32

In [85]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\viach\AppData\Local\Temp\ipykernel_3188\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

# #33

In [86]:
print(np.datetime64('today')-1)
print(np.datetime64('nat'))
# print(np.datetime64('yesterday'))
print(np.datetime64('nat')+1)
print(np.datetime64('nat')-1)
print(np.datetime64('today')+1)
print(np.datetime64('today'))
# print(np.datetime64('tomorrow'))

2025-03-24
NaT
NaT
NaT
2025-03-26
2025-03-25


# #34

In [87]:
start_date = np.datetime64('2025', 'D')
end_date = np.datetime64('2025-03', 'D')
z = np.arange(start_date, end_date)
print(z)


['2025-01-01' '2025-01-02' '2025-01-03' '2025-01-04' '2025-01-05'
 '2025-01-06' '2025-01-07' '2025-01-08' '2025-01-09' '2025-01-10'
 '2025-01-11' '2025-01-12' '2025-01-13' '2025-01-14' '2025-01-15'
 '2025-01-16' '2025-01-17' '2025-01-18' '2025-01-19' '2025-01-20'
 '2025-01-21' '2025-01-22' '2025-01-23' '2025-01-24' '2025-01-25'
 '2025-01-26' '2025-01-27' '2025-01-28' '2025-01-29' '2025-01-30'
 '2025-01-31' '2025-02-01' '2025-02-02' '2025-02-03' '2025-02-04'
 '2025-02-05' '2025-02-06' '2025-02-07' '2025-02-08' '2025-02-09'
 '2025-02-10' '2025-02-11' '2025-02-12' '2025-02-13' '2025-02-14'
 '2025-02-15' '2025-02-16' '2025-02-17' '2025-02-18' '2025-02-19'
 '2025-02-20' '2025-02-21' '2025-02-22' '2025-02-23' '2025-02-24'
 '2025-02-25' '2025-02-26' '2025-02-27' '2025-02-28']


# #37.1

In [88]:
n, m = 3, 5
k = 6
Z = np.zeros((n, m)) + np.arange(k, k+m)
Z

array([[ 6.,  7.,  8.,  9., 10.],
       [ 6.,  7.,  8.,  9., 10.],
       [ 6.,  7.,  8.,  9., 10.]])

# #37.2

In [89]:
n, m = 3, 5
k = 6
Z = np.zeros((n, m)) + np.arange(k, k + n).reshape(n, 1)
Z

array([[6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8.]])

# #38

In [90]:
V = range(10)
Z = np.fromiter(V, dtype=float, count=-1)
Z


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

# #39.1

In [91]:
a = 0
b = 1
n = 10

Z = np.around(np.linspace(a, b, n + 2, )[1:-1], decimals=3)
Z


array([0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818,
       0.909])

# #39.2

In [92]:
a = 1
b = 1000
n = 4
Z = np.around(np.geomspace(a, b, num=n), decimals=3)
Z


array([   1.,   10.,  100., 1000.])

# 40

In [95]:
seed = 42
n = 10
Z = np.sort(np.random.RandomState(seed).rand(n))
Z

array([0.05808361, 0.15599452, 0.15601864, 0.37454012, 0.59865848,
       0.60111501, 0.70807258, 0.73199394, 0.86617615, 0.95071431])