In [98]:
import numpy as np

In [99]:
np.__version__

'2.1.2'

In [100]:
n = 5
Z = np.zeros(n)
Z

array([0., 0., 0., 0., 0.])

In [101]:
l = ['2', '3', 'int']
if l[-1].isnumeric(): 
    l = list(map(int, l))
    Z = np.zeros(l)
else:
    dt = l[-1]
    l = list(map(int, l[:-1]))
    Z = np.zeros(l, dtype=dt)
Z

array([[0, 0, 0],
       [0, 0, 0]])

In [102]:
Z.size*Z.itemsize

48

In [103]:
np.info(np.add)
np.info(np.array)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [104]:
n = 10
x = 5
Z = np.zeros(n)
Z[x] = 1

In [105]:
n = 5
m = 10
Z = np.arange(n, m+1)
Z

array([ 5,  6,  7,  8,  9, 10])

In [106]:
Z[::-1]

array([10,  9,  8,  7,  6,  5])

In [107]:
n = 12
m, k = list(map(int, ('3 4'.split())))
Z = np.arange(n).reshape(m, k)
Z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
Z = np.array([1, 0, 2, 0, 3, 0, 4])
NonZerros = np.nonzero(Z)
NonZerros

(array([0, 2, 4, 6]),)

In [121]:
Z = np.array([[1, 0, 2, 0], [ 3, 0, 4, 5]])
print(Z[Z>3])

[4 5]
