In [171]:
import numpy as np

In [172]:
Y = np.array([[1, 2], [2, 1]])
mu = Y.mean()
sigma = Y.std()
Z = np.around((Y - mu) / sigma, 2)
Z

array([[-1.,  1.],
       [ 1., -1.]])

## Скалярний добуток векторів

In [173]:
A = np.array([1.5, 2.5, 3.5])
B = np.array([4, 5, 6])
Z = np.dot(A, B)

## Добуток матриць

In [174]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[11.5], [12.5], [13.5]])
if A.shape[1] == B.shape[0]:
    Z = np.dot(A, B)
else: Z = 'Упс! Что-то пошло не так...'

## Зміна знаку частини матриці

In [175]:
Z = np.arange(11)
print(Z)
Z[(Z>3)&(Z<9)] *= (-1)
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [176]:
A = np.array([-3.1, -5.9, 0, 2.2, 9.8])
A[A<0] = np.floor(A[A<0])
A[A>0] = np.ceil(A[A>0])
Z = A
Z

array([-4., -6.,  0.,  3., 10.])

In [177]:
A = np.array([0, 9, 7, 1, 3, 7, 5, 2, 5, 1])
B = np.array([3, 1, 3, 7, 4, 1, 8, 1, 1, 8])
Z = np.array(sorted(set(A) & set(B)))
print(Z)

[1 3 7]
