In [320]:
import numpy as np

In [321]:
n = 4
Z = np.eye(n)
Z

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [322]:
n, m, l = map(int, '2 2 2'.split())
np.random.seed(42)
Z = np.random.random([n, m, l])
Z

array([[[0.37454012, 0.95071431],
        [0.73199394, 0.59865848]],

       [[0.15601864, 0.15599452],
        [0.05808361, 0.86617615]]])

In [323]:
n, m = map(int, '3 4'.split())
np.random.seed(42)
Z = np.random.random([n, m])
print(Z.min())
print(Z.max())

0.020584494295802447
0.9699098521619943


In [324]:
print(Z.mean())

0.5159884754987122


In [325]:
print(Z.mean(axis=0).min())
print(Z.mean(axis=0).max())

0.270220682758469
0.8115814940446553


In [326]:
n, m = map(int, '10 10'.split())
Z = np.ones([n, m])
Z[1 : -1, 1 : -1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [327]:
Z = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)
# Z = np.pad(Z, [1], 'constant', constant_values=(0))

In [328]:
n = 3
Z = np.diagflat([i for i in np.arange(1, n+1)])
Z

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [329]:
x, k = -1, 2
Z = np.diagflat([i for i in np.arange(1, k+1)], x)
Z

array([[0, 0, 0],
       [1, 0, 0],
       [0, 2, 0]])

In [330]:
n, m = map(int, '3 5'.split())
arr = np.array([[0, 1], [1, 0]])
Z = np.tile(arr, [int(np.ceil(n/2)), int(np.ceil(m/2))])
Z = Z[:n, :m]
Z

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [332]:
i = 5
Z = np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
print(list(np.unravel_index(i, Z.shape)))

[np.int64(1), np.int64(1)]
